#[path = "../src/image_edit.rs"] mod image_edit;
#[path = "../src/text_edit.rs"] mod text_edit;
use lopdf::{content::{Content,Operation},dictionary,Dictionary,Document,Object,Stream};
use text_edit::{inspect_text_run,replace_text_run};

fn fixture(text:&str)->Vec<u8>{let mut d=Document::with_version("1.7");let pages=d.new_object_id();let font=d.add_object(dictionary!{"Type"=>"Font","Subtype"=>"Type1","BaseFont"=>"Helvetica","Encoding"=>"WinAnsiEncoding"});let content=Content{operations:vec![Operation::new("BT",vec![]),Operation::new("Tf",vec![Object::Name(b"F1".to_vec()),12.into()]),Operation::new("Tm",vec![1.into(),0.into(),0.into(),1.into(),20.into(),50.into()]),Operation::new("Tj",vec![Object::string_literal(text)]),Operation::new("ET",vec![])]}.encode().unwrap();let stream=d.add_object(Stream::new(Dictionary::new(),content));let page=d.add_object(dictionary!{"Type"=>"Page","Parent"=>pages,"MediaBox"=>vec![0.into(),0.into(),200.into(),100.into()],"Resources"=>dictionary!{"Font"=>dictionary!{"F1"=>font}},"Contents"=>stream});d.objects.insert(pages,dictionary!{"Type"=>"Pages","Count"=>1,"Kids"=>vec![Object::Reference(page)]}.into());let root=d.add_object(dictionary!{"Type"=>"Catalog","Pages"=>pages});d.trailer.set("Root",root);d.reference_table.cross_reference_type=lopdf::xref::XrefType::CrossReferenceTable;d.trailer.remove(b"Type");let mut b=Vec::new();d.save_to(&mut b).unwrap();b}

#[test]fn exact_width_replacement_preserves_graph(){let source=fixture("123");let target=inspect_text_run(&source,1).unwrap();assert_eq!(target.text,"123");let out=replace_text_run(&source,1,"789").unwrap();assert_eq!(inspect_text_run(&out,1).unwrap().text,"789");}
#[test]fn rejects_length_width_unicode_and_trailing(){let source=fixture("ABC");assert!(replace_text_run(&source,1,"AB").is_err());assert!(replace_text_run(&source,1,"III").is_err());assert!(replace_text_run(&source,1,"café").is_err());let mut tail=source;tail.extend_from_slice(b"SECRET");assert!(inspect_text_run(&tail,1).is_err());}
#[test]fn rejects_fake_final_eof_and_prefix_junk(){let source=fixture("123");let mut suffix=source.clone();suffix.extend_from_slice(b"\n%SECRET\n%%EOF\n");assert!(inspect_text_run(&suffix,1).is_err());let mut prefix=b"SECRET\n".to_vec();prefix.extend_from_slice(&source);assert!(inspect_text_run(&prefix,1).is_err());}
#[test]fn rejects_extra_operators_fonts_and_graph_channels(){let source=fixture("123");let mut d=Document::load_mem(&source).unwrap();let page=d.get_pages()[&1];let id=d.get_dictionary(page).unwrap().get(b"Contents").unwrap().as_reference().unwrap();let s=d.get_object_mut(id).unwrap().as_stream_mut().unwrap();let mut c=Content::decode(&s.content).unwrap();c.operations.insert(0,Operation::new("q",vec![]));s.set_content(c.encode().unwrap());let mut b=Vec::new();d.save_to(&mut b).unwrap();assert!(inspect_text_run(&b,1).is_err());let mut d=Document::load_mem(&source).unwrap();d.add_object(Object::string_literal("secret"));let mut b=Vec::new();d.save_to(&mut b).unwrap();assert!(inspect_text_run(&b,1).is_err());}
