[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$ProjectRoot,[Parameter(Mandatory=$true)][string]$TargetSourceRoot,[Parameter(Mandatory=$true)][string]$DraftProofRoot,[Parameter(Mandatory=$true)][string]$AssetRoot,[Parameter(Mandatory=$true)][string]$WorkRoot,[Parameter(Mandatory=$true)][string]$OutputRoot,[Parameter(Mandatory=$true)][string]$WebDriverRoot,
 [Parameter(Mandatory=$true)][string]$WorkflowSourceRevision,[Parameter(Mandatory=$true)][string]$DraftProofWorkflowRevision,[Parameter(Mandatory=$true)][string]$DraftProofRunId,[Parameter(Mandatory=$true)][string]$DraftProofWorkflowId,[Parameter(Mandatory=$true)][string]$DraftProofArtifactId,[Parameter(Mandatory=$true)][string]$DraftProofArtifactName,[Parameter(Mandatory=$true)][string]$DraftProofArtifactBytes,[Parameter(Mandatory=$true)][string]$DraftProofArtifactDigest,[Parameter(Mandatory=$true)][string]$DraftProofReceiptBytes,[Parameter(Mandatory=$true)][string]$DraftProofReceiptSha256,
 [Parameter(Mandatory=$true)][string]$TargetVersion,[Parameter(Mandatory=$true)][string]$TargetTag,[Parameter(Mandatory=$true)][string]$TargetSourceRevision,[Parameter(Mandatory=$true)][string]$TargetReleaseId,[Parameter(Mandatory=$true)][string]$InstallerAssetId,[Parameter(Mandatory=$true)][string]$InstallerName,[Parameter(Mandatory=$true)][string]$InstallerBytes,[Parameter(Mandatory=$true)][string]$InstallerSha256,[Parameter(Mandatory=$true)][string]$SignatureAssetId,[Parameter(Mandatory=$true)][string]$SignatureBytes,[Parameter(Mandatory=$true)][string]$SignatureSha256,[Parameter(Mandatory=$true)][string]$ManifestAssetId,[Parameter(Mandatory=$true)][string]$ManifestBytes,[Parameter(Mandatory=$true)][string]$ManifestSha256,[Parameter(Mandatory=$true)][string]$ExpectedPublisher,
 [scriptblock]$RuntimeProvider
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'installed-image-page-tools.ps1')
. (Join-Path $PSScriptRoot 'ocr/installer-package.ps1')
. (Join-Path $PSScriptRoot 'ocr/windows-signing.ps1')

function Import-CommentsFormsFunctions { param([string]$Path,[string[]]$Names)
 $tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($Path,[ref]$tokens,[ref]$errors);if($errors.Count){throw 'A trusted comments/forms helper did not parse.'}
 foreach($name in $Names){$node=$ast.Find({param($value)$value-is[Management.Automation.Language.FunctionDefinitionAst]-and$value.Name-ceq$name},$true);if(-not$node){throw "Trusted comments/forms helper is missing: $name"};Set-Item -Path ("Function:script:"+$name) -Value $node.Body.GetScriptBlock()}
}
Import-CommentsFormsFunctions (Join-Path $PSScriptRoot 'verify-signed-ocr-upgrade.ps1') @('Assert-ExactProperties','Assert-FileReceipt','Resolve-RunnerPath','Assert-FreshInstallFacts','Get-FreshInstallFacts','Get-ConflictingProcessFacts','Invoke-BoundedSilentInstaller','Get-InstallFacts','Assert-InstallFacts','Assert-ReceiptValue','Assert-ReceiptFileObject','Get-UniqueResource')
Import-CommentsFormsFunctions (Join-Path $PSScriptRoot 'verify-default-expanded-page-tools.ps1') @('Assert-DefaultDraftReceipt','Assert-InstalledDefaultResources','Invoke-OwnedCleanup','Assert-EmptyProcessFacts','Assert-OwnedCleanupState','Complete-PrimaryAndCleanup')

$script:CommentsFormsPaths=@('src/App.tsx','src/bridge.ts','src/CommentLayer.tsx','src/CommentEditor.tsx','src/CommentsPanel.tsx','src/FillFormsDialog.tsx','src-tauri/src/comments.rs','src-tauri/src/forms.rs','src-tauri/src/service.rs','src-tauri/src/main.rs','src-tauri/tests/fixtures/reportlab-mixed-fields.pdf','src-tauri/tests/fixtures/reportlab-mixed-fields.py','src-tauri/tests/fixtures/reportlab-radio-fields.pdf','src-tauri/tests/fixtures/reportlab-radio-fields.py','src-tauri/tests/fixtures/reportlab-choice-fields.pdf','src-tauri/tests/fixtures/reportlab-choice-fields.py','src-tauri/tauri.conf.json')

function Assert-CommentsFormsSourceParity {
 foreach($path in $script:CommentsFormsPaths){$target=(& git -C $ProjectRoot rev-parse "$TargetSourceRevision`:$path").Trim();$current=(& git -C $ProjectRoot rev-parse "HEAD`:$path").Trim();if($LASTEXITCODE-ne0-or$target-cne$current){throw "Installed comments/forms source parity failed: $path"}}
 $app=(& git -C $ProjectRoot show "$TargetSourceRevision`:src/App.tsx")-join"`n";$markers=@('createComment','createHighlight','documentAnnotations','saveCopy','documentFormFields','fillFormCopy','Fill forms','Add area highlight');foreach($marker in $markers){if(-not$app.Contains($marker,[StringComparison]::Ordinal)){throw 'Target application lacks an exact comments/forms selector marker.'}}
 return [ordered]@{exactFeatureBlobsMatched=$true;featureBlobCount=17;selectorMarkerCount=8}
}

function Get-CommentsFormsReceipt { param([string]$Path)
 $item=Get-Item -LiteralPath $Path -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint-or$item.Length-lt1){throw 'A comments/forms file receipt is unsafe.'};return [pscustomobject][ordered]@{bytes=[uint64]$item.Length;sha256=Get-ExactSha256 -Path $Path}
}

function Invoke-CommentsFormsNativeSave { param([string]$SessionId,[int]$ProcessId,[long]$ProcessStartUtcTicks,[string]$OutputPath,[string]$ButtonLabel,[datetime]$Deadline)
 if(Test-Path -LiteralPath $OutputPath){throw 'A comments/forms output path must be fresh.'};Assert-NoReparseAncestors -Path $OutputPath
 $baseline=@(Get-ProcessNativeWindowSnapshot -ProcessId $ProcessId -Deadline $Deadline -TopLevelOnly);if($baseline.Count-lt1){throw 'Comments/forms native Save baseline was empty.'}
 $label=$ButtonLabel|ConvertTo-Json -Compress;$clicked=Invoke-WebDriverScript -SessionId $SessionId -Deadline $Deadline -Script "const n=$label,b=[...document.querySelectorAll('button')].filter(x=>x.textContent.trim()===n&&!x.disabled);if(b.length===1)b[0].click();return b.length===1;"
 if($clicked-isnot[bool]-or-not$clicked){throw 'The exact comments/forms Save control was unavailable.'}
 $binding=Wait-NewProcessNativeWindowSurface -ProcessId $ProcessId -Baseline $baseline -AnchorNames @('Save') -AnchorControlTypes @('ControlType.Button') -Stage 'save-output-dialog' -Deadline $Deadline
 $roles=Get-ValidatedBindingNativeRoles -Binding $binding;if($null-eq$roles-or$null-eq$roles.PSObject.Properties['save']-or$null-eq$roles.PSObject.Properties['filenameEdit']){throw 'Comments/forms Save dialog lacked exact native roles.'}
 $remaining=[int][Math]::Min(120000,[Math]::Max(1,[Math]::Ceiling(($Deadline-[datetime]::UtcNow).TotalMilliseconds)));$tick=[Environment]::TickCount64+$remaining
 Set-BoundNativeSaveFileNameExact -ProcessId $ProcessId -ProcessStartUtcTicks $ProcessStartUtcTicks -Binding $binding -Value $OutputPath -DeadlineTickCount $tick
 Invoke-BoundNativeSaveButtonExact -ProcessId $ProcessId -ProcessStartUtcTicks $ProcessStartUtcTicks -Binding $binding -DeadlineTickCount $tick
 Wait-BoundProcessUiSurfaceClosed -ProcessId $ProcessId -Binding $binding -Stage 'save-output-dialog' -Deadline $Deadline -ProcessStartUtcTicks $ProcessStartUtcTicks -ExpectedNativeSaveFileName $OutputPath -ActionTransport 'native-bm-click-delivered'
 $null=Wait-ImagePageStableFile -Path $OutputPath -Deadline $Deadline;return Get-CommentsFormsReceipt $OutputPath
}

function Open-CommentsFormsFile { param($Context,[string]$Path)
 $null=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'comments/forms home' -Script (Get-ReadingHomeScript) -Predicate {param($v)[bool]$v.ready-and[string]$v.title-ceq'PDF Workstation'}
 return Open-ReadingUserFile -SessionId $Context.SessionId -ApplicationProcessId $Context.ApplicationProcessId -ApplicationProcessStartUtcTicks $Context.ApplicationProcessStartUtcTicks -Path $Path -Deadline $Context.Deadline
}

function Invoke-CommentsCreateSession { param($Context,[string]$SourcePath,[string]$OutputPath)
 $category=Open-CommentsFormsFile $Context $SourcePath
 $script=@'
const button=n=>[...document.querySelectorAll('button')].find(x=>x.getAttribute('aria-label')===n&&!x.disabled);
const fire=(element,type,x,y,id)=>element.dispatchEvent(new PointerEvent(type,{bubbles:true,button:0,buttons:type==='pointerup'?0:1,clientX:x,clientY:y,pointerId:id,pointerType:'mouse'}));
const input=(element,value)=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}));};
const page=document.querySelector('img[alt="Page 1"]'),layer=document.querySelector('[data-testid="comment-layer"]');if(!page||!layer||!button('Add comment'))return false;
button('Add comment').click();let r=page.getBoundingClientRect();fire(layer,'pointerdown',r.left+r.width*.25,r.top+r.height*.25,11);return true;
'@
 $started=Invoke-WebDriverScript -SessionId $Context.SessionId -Deadline $Context.Deadline -Script $script;if($started-isnot[bool]-or-not$started){throw 'Exact sticky-comment creation controls were unavailable.'}
 $null=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'sticky comment editor' -Script "const t=document.querySelector('textarea[aria-label=`"Comment text`"]');if(t){Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(t,'Installed sticky receipt');t.dispatchEvent(new Event('input',{bubbles:true}));}const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Save comment'&&!x.disabled);if(b)b.click();return !!t&&!!b;" -Predicate {param($v)$v-is[bool]-and$v}
 $null=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'sticky persisted' -Script "return [...document.querySelectorAll('aside[aria-label=`"Comments`"] span')].some(x=>x.textContent.trim()==='Installed sticky receipt');" -Predicate {param($v)$v-is[bool]-and$v}
 $area=Invoke-WebDriverScript -SessionId $Context.SessionId -Deadline $Context.Deadline -Script "const b=[...document.querySelectorAll('button')].find(x=>x.getAttribute('aria-label')==='Add area highlight'&&!x.disabled);if(!b)return false;b.click();const p=document.querySelector('img[alt=`"Page 1`"]'),l=document.querySelector('[data-testid=`"comment-layer`"]');if(!p||!l)return false;const r=p.getBoundingClientRect(),e=(t,x,y)=>l.dispatchEvent(new PointerEvent(t,{bubbles:true,button:0,buttons:t==='pointerup'?0:1,clientX:x,clientY:y,pointerId:12,pointerType:'mouse'}));e('pointerdown',r.left+r.width*.55,r.top+r.height*.55);e('pointermove',r.left+r.width*.75,r.top+r.height*.7);e('pointerup',r.left+r.width*.75,r.top+r.height*.7);return true;"
 if($area-isnot[bool]-or-not$area){throw 'Exact area-highlight creation controls were unavailable.'}
 $null=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'area highlight editor' -Script "const t=document.querySelector('textarea[aria-label=`"Highlight description`"]');if(t){Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(t,'Installed area receipt');t.dispatchEvent(new Event('input',{bubbles:true}));}const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Save area highlight'&&!x.disabled);if(b)b.click();return !!t&&!!b;" -Predicate {param($v)$v-is[bool]-and$v}
 $null=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'area persisted' -Script "return [...document.querySelectorAll('aside[aria-label=`"Comments`"] span')].some(x=>x.textContent.trim()==='Installed area receipt');" -Predicate {param($v)$v-is[bool]-and$v}
 $receipt=Invoke-CommentsFormsNativeSave -SessionId $Context.SessionId -ProcessId $Context.ApplicationProcessId -ProcessStartUtcTicks $Context.ApplicationProcessStartUtcTicks -OutputPath $OutputPath -ButtonLabel 'Save a copy' -Deadline $Context.Deadline
 return [pscustomobject][ordered]@{nativeFilenameControlCategory=$category;output=$receipt;stickyCreated=$true;areaHighlightCreated=$true}
}

function Invoke-CommentsReopenSession { param($Context,[string]$Path)
 $null=Open-CommentsFormsFile $Context $Path;$state=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'reopened comments' -Script "const b=document.querySelector('button[aria-label=`"Comments`"]');if(b&&!b.disabled)b.click();const rows=[...document.querySelectorAll('aside[aria-label=`"Comments`"] button')];return {sticky:rows.filter(x=>x.textContent.includes('Installed sticky receipt')&&x.textContent.includes('Comment · Page 1')).length,area:rows.filter(x=>x.textContent.includes('Installed area receipt')&&x.textContent.includes('Highlight · Page 1')).length};" -Predicate {param($v)[int]$v.sticky-eq1-and[int]$v.area-eq1}
 return [pscustomobject][ordered]@{stickyCount=[int]$state.sticky;areaHighlightCount=[int]$state.area;page=1;pixelAppearanceVerified=$false;nativePdfSemanticVerified=$false;selectedTextHighlightVerified=$false}
}

function Invoke-FormSession { param($Context,[string]$SourcePath,[string]$OutputPath,[string]$Kind,[bool]$Reopen)
 $null=Open-CommentsFormsFile $Context $SourcePath
 $kindJson=$Kind|ConvertTo-Json -Compress;$reopenJson=if($Reopen){'true'}else{'false'}
 $state=Wait-WebDriverOracle -SessionId $Context.SessionId -Deadline $Context.Deadline -Kind 'form fields' -Script "const kind=$kindJson,reopen=$reopenJson,b=document.querySelector('button[aria-label=`"Fill existing fields`"]');if(b&&!b.disabled)b.click();const d=document.querySelector('dialog[aria-labelledby=`"fill-forms-title`"]');if(!d)return null;const set=(e,v)=>{const p=e.tagName==='SELECT'?HTMLSelectElement.prototype:e.type==='checkbox'?HTMLInputElement.prototype:e.type==='radio'?HTMLInputElement.prototype:HTMLInputElement.prototype;const key=e.type==='checkbox'||e.type==='radio'?'checked':'value';Object.getOwnPropertyDescriptor(p,key).set.call(e,v);e.dispatchEvent(new Event('change',{bubbles:true}));e.dispatchEvent(new Event('input',{bubbles:true}));};let initial='',expected='';if(kind==='mixed'){const n=d.querySelector('input[aria-label=`"Name`"]'),c=d.querySelector('input[aria-label=`"Consent, page 1`"]');initial=(n?.value||'')+'|'+!!c?.checked;expected='Installed Mixed|true';if(!reopen){set(n,'Installed Mixed');set(c,true)}}else if(kind==='radio'){const chosen=[...d.querySelectorAll('input[type=radio]')].find(x=>x.checked);initial=chosen?.getAttribute('aria-label')||'';expected='Preference: Choice A, page 1';if(!reopen){const e=d.querySelector('input[aria-label=`"Preference: Choice A, page 1`"]');if(e)set(e,true)}}else{const fields=[...d.querySelectorAll('select')];initial=fields.map(x=>x.value).join('|');expected='north-001|print-001';if(!reopen&&fields.length===2){set(fields[0],'north-001');set(fields[1],'print-001')}}return {initial,expected,ready:initial.length>0,matched:reopen&&initial===expected};" -Predicate {param($v)$null-ne$v-and[bool]$v.ready-and(-not$Reopen-or[bool]$v.matched)}
 if($Reopen){return [pscustomobject][ordered]@{kind=$Kind;initial=[string]$state.initial;reopenedValuesMatched=$true;pixelAppearanceVerified=$false;nativePdfSemanticVerified=$false}}
 $receipt=Invoke-CommentsFormsNativeSave -SessionId $Context.SessionId -ProcessId $Context.ApplicationProcessId -ProcessStartUtcTicks $Context.ApplicationProcessStartUtcTicks -OutputPath $OutputPath -ButtonLabel 'Save filled copy' -Deadline $Context.Deadline
 return [pscustomobject][ordered]@{kind=$Kind;sourceValues=[string]$state.initial;expectedOutputValues=[string]$state.expected;output=$receipt;saveDialogVerified=$true}
}

function Invoke-InstalledCommentsFormsRuntime { param([string]$ApplicationPath,[string]$TauriDriverPath,[string]$EdgeDriverPath,[string]$SettingsRoot,[string]$Work,[string]$ExpectedEdgeDriverVersion,$CommentFixture,[object[]]$Fixtures)
 $commentSource=[string]$CommentFixture.path;$commentOutput=Join-Path $Work 'comments-saved.pdf'
 $created=Invoke-FreshInstalledImagePageToolsSession -ApplicationPath $ApplicationPath -TauriDriverPath $TauriDriverPath -EdgeDriverPath $EdgeDriverPath -ProfileRoot (Join-Path $Work 'comments-create-profile') -SettingsRoot $SettingsRoot -ExpectedEdgeDriverVersion $ExpectedEdgeDriverVersion -SessionCallback ({param($c)Invoke-CommentsCreateSession $c $commentSource $commentOutput}.GetNewClosure())
 $reopened=Invoke-FreshInstalledImagePageToolsSession -ApplicationPath $ApplicationPath -TauriDriverPath $TauriDriverPath -EdgeDriverPath $EdgeDriverPath -ProfileRoot (Join-Path $Work 'comments-reopen-profile') -SettingsRoot $SettingsRoot -ExpectedEdgeDriverVersion $ExpectedEdgeDriverVersion -SessionCallback ({param($c)Invoke-CommentsReopenSession $c $commentOutput}.GetNewClosure())
 $forms=@();foreach($fixture in $Fixtures){$output=Join-Path $Work ("form-$($fixture.kind)-saved.pdf");$write=Invoke-FreshInstalledImagePageToolsSession -ApplicationPath $ApplicationPath -TauriDriverPath $TauriDriverPath -EdgeDriverPath $EdgeDriverPath -ProfileRoot (Join-Path $Work ("form-$($fixture.kind)-write-profile")) -SettingsRoot $SettingsRoot -ExpectedEdgeDriverVersion $ExpectedEdgeDriverVersion -SessionCallback ({param($c)Invoke-FormSession $c $fixture.path $output $fixture.kind $false}.GetNewClosure());$read=Invoke-FreshInstalledImagePageToolsSession -ApplicationPath $ApplicationPath -TauriDriverPath $TauriDriverPath -EdgeDriverPath $EdgeDriverPath -ProfileRoot (Join-Path $Work ("form-$($fixture.kind)-read-profile")) -SettingsRoot $SettingsRoot -ExpectedEdgeDriverVersion $ExpectedEdgeDriverVersion -SessionCallback ({param($c)Invoke-FormSession $c $output $output $fixture.kind $true}.GetNewClosure());$forms+=[pscustomobject][ordered]@{kind=$fixture.kind;source=$fixture.receipt;write=$write;reopen=$read}}
 return [pscustomobject][ordered]@{comments=[pscustomobject][ordered]@{source=$CommentFixture.receipt;write=$created;reopen=$reopened};forms=$forms}
}

function Assert-CommentsFormsRuntimeReceipt { param($Value)
 Assert-ExactProperties $Value @('comments','forms') 'Comments/forms runtime receipt';if(@($Value.forms).Count-ne3){throw 'Exactly three form fixture results are required.'}
 function Assert-BoundedFileReceipt($Receipt,[string]$Kind){Assert-ExactProperties $Receipt @('bytes','sha256') $Kind;if([uint64]$Receipt.bytes-lt1-or[uint64]$Receipt.bytes-gt256MB-or[string]$Receipt.sha256-cnotmatch'^[A-F0-9]{64}$'){throw "$Kind is malformed."}}
 function Assert-SessionCleanup($Session,[string]$Kind){if(-not[bool]$Session.sessionDeleted-or-not[bool]$Session.ownedProcessTreeStopped-or[int]$Session.relevantProcessesRemaining-ne0){throw "$Kind cleanup was not exact."}}
 Assert-ExactProperties $Value.comments @('source','write','reopen') 'Comments runtime';Assert-BoundedFileReceipt $Value.comments.source 'Comments source receipt'
 Assert-ExactProperties $Value.comments.write @('nativeDriverVersion','returnedRuntimeVersion','profileBinding','nativeFilenameControlCategory','output','stickyCreated','areaHighlightCreated','sessionDeleted','ownedProcessTreeStopped','relevantProcessesRemaining') 'Comments write session';Assert-BoundedFileReceipt $Value.comments.write.output 'Comments output receipt';Assert-SessionCleanup $Value.comments.write 'Comments write session'
 Assert-ExactProperties $Value.comments.reopen @('nativeDriverVersion','returnedRuntimeVersion','profileBinding','stickyCount','areaHighlightCount','page','pixelAppearanceVerified','nativePdfSemanticVerified','selectedTextHighlightVerified','sessionDeleted','ownedProcessTreeStopped','relevantProcessesRemaining') 'Comments reopen session';Assert-SessionCleanup $Value.comments.reopen 'Comments reopen session'
 if(-not[bool]$Value.comments.write.stickyCreated-or-not[bool]$Value.comments.write.areaHighlightCreated-or[bool]$Value.comments.reopen.pixelAppearanceVerified-or[bool]$Value.comments.reopen.nativePdfSemanticVerified-or[bool]$Value.comments.reopen.selectedTextHighlightVerified-or[int]$Value.comments.reopen.stickyCount-ne1-or[int]$Value.comments.reopen.areaHighlightCount-ne1){throw 'Comments runtime receipt exceeded or missed its exact claim.'}
 $expected=@{mixed=@('Original|false','Installed Mixed|true');radio=@('Preference: Choice B, page 1','Preference: Choice A, page 1');choice=@('south-002|email-002','north-001|print-001')}
 $kinds=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal)
 foreach($form in @($Value.forms)){
  Assert-ExactProperties $form @('kind','source','write','reopen') 'Form runtime';Assert-BoundedFileReceipt $form.source 'Form source receipt'
  Assert-ExactProperties $form.write @('nativeDriverVersion','returnedRuntimeVersion','profileBinding','kind','sourceValues','expectedOutputValues','output','saveDialogVerified','sessionDeleted','ownedProcessTreeStopped','relevantProcessesRemaining') 'Form write session';Assert-BoundedFileReceipt $form.write.output 'Form output receipt';Assert-SessionCleanup $form.write 'Form write session'
  Assert-ExactProperties $form.reopen @('nativeDriverVersion','returnedRuntimeVersion','profileBinding','kind','initial','reopenedValuesMatched','pixelAppearanceVerified','nativePdfSemanticVerified','sessionDeleted','ownedProcessTreeStopped','relevantProcessesRemaining') 'Form reopen session';Assert-SessionCleanup $form.reopen 'Form reopen session'
  $pin=$expected[[string]$form.kind];if($null-eq$pin-or-not$kinds.Add([string]$form.kind)-or[string]$form.write.kind-cne[string]$form.kind-or[string]$form.reopen.kind-cne[string]$form.kind-or[string]$form.write.sourceValues-cne$pin[0]-or[string]$form.write.expectedOutputValues-cne$pin[1]-or[string]$form.reopen.initial-cne$pin[1]-or-not[bool]$form.write.saveDialogVerified-or-not[bool]$form.reopen.reopenedValuesMatched-or[bool]$form.reopen.pixelAppearanceVerified-or[bool]$form.reopen.nativePdfSemanticVerified){throw 'Form runtime receipt exceeded or missed its exact controlled-fixture claim.'}
 }
 if($kinds.Count-ne3){throw 'The exact controlled form kind set was not verified.'}
}

function ConvertTo-CommentsFormsPublicRuntime { param($Value)
 return [ordered]@{
  comments=[ordered]@{sourceBytes=[uint64]$Value.comments.source.bytes;sourceSha256=[string]$Value.comments.source.sha256;outputBytes=[uint64]$Value.comments.write.output.bytes;outputSha256=[string]$Value.comments.write.output.sha256;stickyCount=[int]$Value.comments.reopen.stickyCount;areaHighlightCount=[int]$Value.comments.reopen.areaHighlightCount;saveDialogVerified=$true;freshProcessReopenVerified=$true;sourcePreserved=$true;pixelAppearanceVerified=$false;nativePdfSemanticVerified=$false;selectedTextHighlightVerified=$false}
  forms=@($Value.forms|ForEach-Object{[ordered]@{kind=[string]$_.kind;sourceBytes=[uint64]$_.source.bytes;sourceSha256=[string]$_.source.sha256;outputBytes=[uint64]$_.write.output.bytes;outputSha256=[string]$_.write.output.sha256;saveDialogVerified=$true;freshProcessReopenVerified=$true;sourcePreserved=$true;pixelAppearanceVerified=$false;nativePdfSemanticVerified=$false}})
 }
}

if($TargetVersion-cnotmatch'^\d+\.\d+\.\d+$'-or$TargetTag-cne('v'+$TargetVersion)){throw 'Target version and stable tag are malformed or inconsistent.'}
$root=Resolve-RunnerPath $WorkRoot $env:RUNNER_TEMP -MustBeFresh;$output=Resolve-RunnerPath $OutputRoot $env:RUNNER_TEMP -MustBeFresh;$assets=Resolve-RunnerPath $AssetRoot $env:RUNNER_TEMP -MustBeFresh;$drivers=Resolve-RunnerPath $WebDriverRoot $env:RUNNER_TEMP -MustExist
$expandedOutput=Join-Path $root 'expanded-proof-output';$expandedWork=Join-Path $root 'expanded-proof-work'
$forward=@{ProjectRoot=$ProjectRoot;TargetSourceRoot=$TargetSourceRoot;DraftProofRoot=$DraftProofRoot;AssetRoot=$assets;WorkRoot=$expandedWork;OutputRoot=$expandedOutput;WebDriverRoot=$drivers;WorkflowSourceRevision=$WorkflowSourceRevision;DraftProofWorkflowRevision=$DraftProofWorkflowRevision;DraftProofRunId=$DraftProofRunId;DraftProofWorkflowId=$DraftProofWorkflowId;DraftProofArtifactId=$DraftProofArtifactId;DraftProofArtifactName=$DraftProofArtifactName;DraftProofArtifactBytes=$DraftProofArtifactBytes;DraftProofArtifactDigest=$DraftProofArtifactDigest;DraftProofReceiptBytes=$DraftProofReceiptBytes;DraftProofReceiptSha256=$DraftProofReceiptSha256;TargetVersion=$TargetVersion;TargetTag=$TargetTag;TargetSourceRevision=$TargetSourceRevision;TargetReleaseId=$TargetReleaseId;InstallerAssetId=$InstallerAssetId;InstallerName=$InstallerName;InstallerBytes=$InstallerBytes;InstallerSha256=$InstallerSha256;SignatureAssetId=$SignatureAssetId;SignatureBytes=$SignatureBytes;SignatureSha256=$SignatureSha256;ManifestAssetId=$ManifestAssetId;ManifestBytes=$ManifestBytes;ManifestSha256=$ManifestSha256;ExpectedPublisher=$ExpectedPublisher}
& (Join-Path $PSScriptRoot 'verify-default-expanded-page-tools.ps1') @forward
$expandedReceipt=Join-Path $expandedOutput 'default-expanded-page-tools-verification.json';$expandedBinding=Get-CommentsFormsReceipt $expandedReceipt
$env:GITHUB_TOKEN=$null;$env:GH_TOKEN=$null
if($env:GITHUB_TOKEN-or$env:GH_TOKEN){throw 'GitHub tokens remained before comments/forms installation or application launch.'}
$sourceBinding=Assert-CommentsFormsSourceParity
$proofFile=@(Get-ChildItem -LiteralPath $DraftProofRoot -Recurse -File -Force);if($proofFile.Count-ne1){throw 'Step 1 proof artifact shape changed.'};$receipt=Get-Content $proofFile[0].FullName -Raw -Encoding UTF8|ConvertFrom-Json;$sets=Assert-DefaultDraftReceipt $receipt
$installer=Join-Path $assets $InstallerName;$installRoot=[IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA 'PDF Workstation')).TrimEnd('\');$settings=[IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA 'local.pdfworkstation.desktop')).TrimEnd('\');$registry='Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\PDF Workstation'
$fresh=Get-FreshInstallFacts $installRoot $settings $registry @($installer);Assert-FreshInstallFacts $fresh;$baseline=Get-ConflictingProcessFacts @($installer);Assert-EmptyProcessFacts $baseline 'Baseline'
$installed=$false;$primary=$null;$cleanup=$null;$final=$null
try{
 Invoke-BoundedSilentInstaller $installer;$installed=$true;$facts=Get-InstallFacts $registry $installRoot;Assert-InstallFacts $facts $TargetVersion $installRoot $receipt.packagedApplication 'Valid' $ExpectedPublisher $true;$resources=Assert-InstalledDefaultResources $installRoot $receipt $sets
 [IO.Directory]::CreateDirectory($settings)|Out-Null;$fixtureRoot=Join-Path $root 'fixtures';[IO.Directory]::CreateDirectory($fixtureRoot)|Out-Null
 $commentPath=Join-Path $fixtureRoot 'comments-source.pdf';Copy-Item -LiteralPath $resources.Welcome.FullName -Destination $commentPath;$commentFixture=[pscustomobject]@{path=$commentPath;receipt=Get-CommentsFormsReceipt $commentPath}
 $specs=@(@('mixed','reportlab-mixed-fields.pdf'),@('radio','reportlab-radio-fields.pdf'),@('choice','reportlab-choice-fields.pdf'));$fixtures=@();foreach($spec in $specs){$source=Join-Path $TargetSourceRoot ('src-tauri/tests/fixtures/'+$spec[1]);$copy=Join-Path $fixtureRoot $spec[1];Copy-Item -LiteralPath $source -Destination $copy;$fixtures+=[pscustomobject]@{kind=$spec[0];path=$copy;receipt=Get-CommentsFormsReceipt $copy}}
 $runtime=if($RuntimeProvider){&$RuntimeProvider $resources $drivers $settings $root $commentFixture $fixtures $receipt}else{Invoke-InstalledCommentsFormsRuntime -ApplicationPath $resources.Application.FullName -TauriDriverPath (Join-Path $drivers 'tauri-driver-install/bin/tauri-driver.exe') -EdgeDriverPath (Join-Path $drivers 'edge-driver/msedgedriver.exe') -SettingsRoot $settings -Work $root -ExpectedEdgeDriverVersion ([string](Get-Content (Join-Path $drivers 'webdriver-receipt.json') -Raw|ConvertFrom-Json).edgeDriver.version) -CommentFixture $commentFixture -Fixtures $fixtures};Assert-CommentsFormsRuntimeReceipt $runtime
 foreach($fixture in @($commentFixture)+$fixtures){Assert-FileReceipt $fixture.path $fixture.receipt.bytes $fixture.receipt.sha256 'Preserved comments/forms source fixture'}
}catch{$primary=$_}finally{try{Invoke-OwnedCleanup $installed $installRoot $settings;$final=Get-ConflictingProcessFacts @($installer);Assert-OwnedCleanupState $registry $installRoot $settings $final}catch{$cleanup=$_}}
Complete-PrimaryAndCleanup $primary $cleanup
[IO.Directory]::CreateDirectory($output)|Out-Null;$record=[ordered]@{schemaVersion=1;scope='Installed sticky-comment, area-highlight, and three controlled form-fixture save/reopen verification. DOM persistence only; no selected-text highlight, native PDF semantic, arbitrary form, or pixel-appearance claim.';workflowSourceRevision=$WorkflowSourceRevision;targetSourceRevision=$TargetSourceRevision;targetVersion=$TargetVersion;step1=[ordered]@{workflowSourceRevision=$DraftProofWorkflowRevision;workflowId=[uint64]$DraftProofWorkflowId;runId=[uint64]$DraftProofRunId;artifactId=[uint64]$DraftProofArtifactId;artifactDigest=$DraftProofArtifactDigest;receiptBytes=[uint64]$DraftProofReceiptBytes;receiptSha256=$DraftProofReceiptSha256};expandedProof=$expandedBinding;sourceBinding=$sourceBinding;runtime=ConvertTo-CommentsFormsPublicRuntime $runtime;limits=[ordered]@{stickyComment=$true;areaHighlight=$true;selectedTextHighlight=$false;controlledFormFixtureCount=3;nativePdfSemanticVerified=$false;pixelAppearanceVerified=$false};cleanup=[ordered]@{silentUninstallCompleted=$true;baseline=$baseline;final=$final;ownedSettingsRemoved=$true}}
$json=$record|ConvertTo-Json -Depth 30;if($json-match'(?i)([A-Z]:\\|\\Users\\|runneradmin|RUNNER_TEMP|GITHUB_TOKEN|GH_TOKEN|AZURE_|TAURI_SIGNING|raw\.log)'){throw 'Comments/forms receipt contains host or credential data.'};[IO.File]::WriteAllText((Join-Path $output 'default-comments-forms-verification.json'),$json,[Text.UTF8Encoding]::new($false))
