import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import App from './App';
import Viewer from './Viewer';
import { documentPageLabels, editPages, openDocument, pageText } from './bridge';
import type { DocumentInfo } from './model';
vi.mock('./bridge', () => ({ native: false, openDocument: vi.fn(), reopenDocument: vi.fn(), closeDocument: vi.fn(), editPages: vi.fn(), saveCopy: vi.fn(), pageText: vi.fn(), createPdfFromImage: vi.fn(), documentPageLabels: vi.fn() }));
vi.mock('./Viewer', () => ({ default: () => <div>Viewer</div> }));
const document = (id: number): DocumentInfo => ({ id, name: `file-${id}.pdf`, path: `C:/file-${id}.pdf`, pages: Array.from({ length: 6 }, () => ({ width: 612, height: 792 })), revision: 0, dirty: false, can_undo: true, can_redo: false });
beforeEach(() => {
  vi.clearAllMocks(); const storage = new Map();
  vi.stubGlobal('window', { localStorage: { getItem: (key: string) => storage.get(key) ?? null, setItem: (key: string, value: string) => storage.set(key, value) }, addEventListener: vi.fn(), removeEventListener: vi.fn() });
});
afterEach(() => vi.unstubAllGlobals());
const tab = (ui: ReactTestRenderer, name: string) => ui.root.findAllByType('button').find(button => button.findAllByType('span').some(span => span.children.includes(name)))!;
const text = (node: unknown): string => Array.isArray(node) ? node.map(text).join('') : typeof node === 'string' ? node : (node && typeof node === 'object' && 'children' in node) ? text((node as { children?: unknown }).children) : '';
async function open(ui: ReactTestRenderer, id: number) {
  vi.mocked(openDocument).mockResolvedValue({ status: 'opened', document: document(id) });
  await act(async () => ui.root.findAllByType('button').find(button => button.children.includes('Open a file'))!.props.onClick());
}
it('restores each tab to its last scrolled or explicitly chosen page', async () => {
  let ui!: ReactTestRenderer; act(() => { ui = create(<App />); });
  await open(ui, 1);
  act(() => ui.root.findByType(Viewer).props.onPage(4));
  await open(ui, 2);
  act(() => ui.root.findByProps({ 'aria-label': 'Page number' }).props.onKeyDown({ key: 'Enter', currentTarget: { value: '3' } }));
  act(() => tab(ui, 'file-1.pdf').props.onClick());
  expect(ui.root.findByType(Viewer).props.target.page).toBe(4);
  act(() => tab(ui, 'file-2.pdf').props.onClick());
  expect(ui.root.findByType(Viewer).props.target.page).toBe(2);
  act(() => ui.unmount());
});
it('clamps the remembered position when page edits shorten a document', async () => {
  let ui!: ReactTestRenderer; act(() => { ui = create(<App />); });
  await open(ui, 1);
  act(() => ui.root.findByType(Viewer).props.onPage(5));
  vi.mocked(editPages).mockResolvedValue({ ...document(1), pages: document(1).pages.slice(0, 2), revision: 1 });
  await act(async () => ui.root.findByProps({ 'aria-label': 'Undo' }).props.onClick());
  await open(ui, 2);
  act(() => tab(ui, 'file-1.pdf').props.onClick());
  expect(ui.root.findByType(Viewer).props.target.page).toBe(1);
  act(() => ui.unmount());
});
it('enables Next on the first page and disables it only at the final page', async () => {
  let ui!: ReactTestRenderer; act(() => { ui = create(<App />); });
  await open(ui, 1);
  const next = () => ui.root.findByProps({ 'aria-label': 'Next page' });
  const previous = () => ui.root.findByProps({ 'aria-label': 'Previous page' });
  expect(previous().props.disabled).toBe(true);
  expect(next().props.disabled).toBe(false);
  for (let page = 1; page < 6; page++) act(() => next().props.onClick());
  expect(ui.root.findByType(Viewer).props.target.page).toBe(5);
  expect(previous().props.disabled).toBe(false);
  expect(next().props.disabled).toBe(true);
  act(() => ui.unmount());
});
it('shows labels as secondary text while numeric navigation stays physical', async () => {
  vi.mocked(documentPageLabels).mockResolvedValue({ documentId: 1, revision: 0, status: 'supported', reason: null, labels: ['Cover', '12', '', '  Ω  ', 'Back', 'End'].map((label, page) => ({ page, label })) });
  let ui!: ReactTestRenderer; act(() => { ui = create(<App />); });
  await open(ui, 1);
  await act(async () => { await Promise.resolve(); await Promise.resolve(); });
  act(() => ui.root.findByProps({ 'aria-label': 'Pages' }).props.onClick());
  const rendered = text(ui.toJSON());
  expect(rendered).toContain('Label: 12');
  expect(rendered).toContain('(blank label)');
  expect(rendered).toContain('Label:   Ω  ');
  act(() => ui.root.findByProps({ 'aria-label': 'Page number' }).props.onKeyDown({ key: 'Enter', currentTarget: { value: '12' } }));
  expect(ui.root.findByType(Viewer).props.target.page).toBe(5);
  act(() => ui.unmount());
});
it('clears labels on revision changes and ignores a stale snapshot', async () => {
  const pending: ((value: unknown) => void)[] = [];
  vi.mocked(documentPageLabels).mockImplementation(() => new Promise<unknown>(resolve => pending.push(resolve)) as Promise<any>);
  let ui!: ReactTestRenderer; act(() => { ui = create(<App />); });
  await open(ui, 1);
  expect(pending).toHaveLength(1);
  vi.mocked(editPages).mockResolvedValue({ ...document(1), revision: 1 });
  await act(async () => ui.root.findByProps({ 'aria-label': 'Undo' }).props.onClick());
  expect(pending).toHaveLength(2);
  await act(async () => pending.shift()!({ documentId: 1, revision: 0, status: 'supported', reason: null, labels: document(1).pages.map((_, page) => ({ page, label: 'stale' })) }));
  expect(text(ui.toJSON())).not.toContain('Label: stale');
  await act(async () => pending.shift()!({ documentId: 1, revision: 1, status: 'supported', reason: null, labels: document(1).pages.map((_, page) => ({ page, label: `new-${page}` })) }));
  expect(text(ui.toJSON())).toContain('Label: new-0');
  act(() => ui.unmount());
});
it('clears page highlights when search closes, the active tab changes, or a revision changes', async () => {
  let ui!: ReactTestRenderer; act(() => { ui = create(<App />); });
  await open(ui, 1);
  vi.mocked(pageText).mockResolvedValue('needle');
  act(() => ui.root.findByProps({ 'aria-label': 'Find text' }).props.onClick());
  act(() => ui.root.findByProps({ maxLength: 500 }).props.onChange({ target: { value: 'needle' } }));
  await act(async () => ui.root.findByType('form').props.onSubmit({ preventDefault: vi.fn() }));
  expect(ui.root.findByType(Viewer).props.search).toMatchObject({ documentId: 1, revision: 0 });
  expect(ui.root.findByType(Viewer).props.search.pages).toContain(0);
  act(() => ui.root.findByProps({ 'aria-label': 'Find text' }).props.onClick());
  expect(ui.root.findByType(Viewer).props.search).toBeNull();
  act(() => ui.root.findByProps({ 'aria-label': 'Find text' }).props.onClick());
  act(() => ui.root.findByProps({ maxLength: 500 }).props.onChange({ target: { value: 'needle' } }));
  await act(async () => ui.root.findByType('form').props.onSubmit({ preventDefault: vi.fn() }));
  await open(ui, 2);
  expect(ui.root.findByType(Viewer).props.search).toBeNull();
  act(() => tab(ui, 'file-1.pdf').props.onClick());
  vi.mocked(editPages).mockResolvedValue({ ...document(1), revision: 1 });
  await act(async () => ui.root.findByProps({ 'aria-label': 'Undo' }).props.onClick());
  expect(ui.root.findByType(Viewer).props.search).toBeNull();
  act(() => ui.unmount());
});
