import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import App from './App';
import type { DocumentInfo } from './model';

const source:DocumentInfo={id:3,name:'source.pdf',path:'C:/source.pdf',pages:[{width:612,height:792},{width:612,height:792}],revision:9,dirty:true,can_undo:true,can_redo:false};
const copy:DocumentInfo={id:4,name:'source-searchable.pdf',path:'C:/source-searchable.pdf',pages:source.pages,revision:0,dirty:false,can_undo:false,can_redo:false};
const request1='11111111-1111-4111-8111-111111111111',request2='22222222-2222-4222-8222-222222222222';
const available={available:true,reason:null,language:'eng',searchablePdfAvailable:true,searchablePdfReason:null,searchablePdfDpi:150,searchablePdfMaxPages:32,searchablePdfMaxPixels:33_554_432,searchablePdfMaxWords:100_000,searchablePdfMaxTextBytes:8_388_608,searchablePdfCharacters:'printable ASCII words only'};
const unavailable={available:false,reason:'OCR is not enabled in this build.',language:null,searchablePdfAvailable:false,searchablePdfReason:'Searchable OCR is not enabled in this build.',searchablePdfDpi:null,searchablePdfMaxPages:32,searchablePdfMaxPixels:33_554_432,searchablePdfMaxWords:100_000,searchablePdfMaxTextBytes:8_388_608,searchablePdfCharacters:null};
const mocks=vi.hoisted(()=>({openDocument:vi.fn(),reopenDocument:vi.fn(),closeDocument:vi.fn(),saveCopy:vi.fn(),ocrCapability:vi.fn(),recognizePageOcr:vi.fn(),createSearchableOcrCopy:vi.fn(),cancelPageOcr:vi.fn()}));
let dragDrop:((event:{payload:{type:string;paths:string[]}})=>void)|null=null,keydown:((event:KeyboardEvent)=>void)|null=null;

vi.mock('@tauri-apps/api/window',()=>({getCurrentWindow:()=>({onCloseRequested:vi.fn().mockResolvedValue(vi.fn()),onDragDropEvent:(handler:typeof dragDrop)=>{dragDrop=handler;return Promise.resolve(vi.fn());}})}));
vi.mock('./bridge',()=>({
  native:true,openDocument:mocks.openDocument,reopenDocument:mocks.reopenDocument,closeDocument:mocks.closeDocument,editPages:vi.fn(),saveCopy:mocks.saveCopy,splitDocument:vi.fn(),cropPages:vi.fn(),resetCrops:vi.fn(),combineDocuments:vi.fn(),insertPagesCopy:vi.fn(),replacePagesCopy:vi.fn(),documentFormFields:vi.fn().mockResolvedValue({status:'unsupported',reason:null,fields:[]}),fillFormCopy:vi.fn(),documentAnnotations:vi.fn().mockResolvedValue({status:'unsupported',reason:null,annotations:[]}),documentPageLabels:vi.fn().mockResolvedValue({documentId:3,revision:9,labels:[null,null]}),createPdfFromImage:vi.fn(),exportPageImage:vi.fn(),redactDocument:vi.fn(),createComment:vi.fn(),updateComment:vi.fn(),deleteComment:vi.fn(),createHighlight:vi.fn(),createTextHighlight:vi.fn(),updateHighlight:vi.fn(),deleteHighlight:vi.fn(),ocrCapability:mocks.ocrCapability,recognizePageOcr:mocks.recognizePageOcr,createSearchableOcrCopy:mocks.createSearchableOcrCopy,cancelPageOcr:mocks.cancelPageOcr,cancelPasswordRequest:vi.fn()
}));
vi.mock('./Viewer',()=>({default:({document}:{document:DocumentInfo})=><div data-viewed-document={document.id}>{document.name}</div>}));
const button=(ui:ReactTestRenderer,text:string)=>ui.root.findAllByType('button').find(item=>item.children.join('')===text)!;
const openMenu=(ui:ReactTestRenderer)=>act(()=>ui.root.findByProps({'aria-expanded':false}).props.onClick());
async function mount(capability:unknown=available){mocks.ocrCapability.mockResolvedValue(capability);let ui!:ReactTestRenderer;await act(async()=>{ui=create(<App/>,{createNodeMock:element=>element.type==='dialog'?{showModal:vi.fn()}:null});});return ui;}
async function openSource(ui:ReactTestRenderer,document:DocumentInfo={...source,pages:[...source.pages]}){mocks.openDocument.mockResolvedValueOnce({status:'opened',document});await act(async()=>button(ui,'Open a file').props.onClick());}
function launch(ui:ReactTestRenderer){openMenu(ui);act(()=>button(ui,'Create searchable OCR copy…').props.onClick());}

beforeEach(()=>{vi.clearAllMocks();dragDrop=null;keydown=null;vi.stubGlobal('window',{localStorage:{getItem:()=>null,setItem:vi.fn()},addEventListener:vi.fn((name:string,handler:(event:KeyboardEvent)=>void)=>{if(name==='keydown')keydown=handler;}),removeEventListener:vi.fn()});vi.stubGlobal('crypto',{randomUUID:vi.fn().mockReturnValueOnce(request1).mockReturnValueOnce(request2)});mocks.cancelPageOcr.mockResolvedValue({requestId:request1,status:'cancelled'});});
afterEach(()=>vi.unstubAllGlobals());

it('keeps searchable OCR unavailable for the default capability',async()=>{const ui=await mount(unavailable);await openSource(ui);openMenu(ui);const action=button(ui,'Create searchable OCR copy…');expect(action.props.disabled).toBe(true);expect(action.props.title).toBe('Searchable OCR is not enabled in this build.');act(()=>ui.unmount());});
it('fails closed when the extended capability is missing or incoherent',async()=>{const ui=await mount({available:true,reason:null,language:'eng'});await openSource(ui);openMenu(ui);expect(button(ui,'Create searchable OCR copy…').props.disabled).toBe(true);expect(button(ui,'Create searchable OCR copy…').props.title).toBe('OCR is unavailable in this build.');act(()=>ui.unmount());});
it('sends the exact captured document, revision, and fresh UUID then opens only the returned copy',async()=>{mocks.createSearchableOcrCopy.mockResolvedValue({path:copy.path,document:copy});const ui=await mount();await openSource(ui);launch(ui);await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(mocks.createSearchableOcrCopy).toHaveBeenCalledWith({requestId:request1,documentId:3,revision:9});expect(ui.root.findAllByProps({'data-viewed-document':4})).toHaveLength(1);expect(JSON.stringify(ui.toJSON())).toContain('source-searchable.pdf');act(()=>ui.unmount());});
it('keeps the source after picker cancellation and uses a new UUID on retry',async()=>{mocks.createSearchableOcrCopy.mockResolvedValueOnce(null).mockResolvedValueOnce({path:copy.path,document:copy});const ui=await mount();await openSource(ui);launch(ui);await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(JSON.stringify(ui.toJSON())).toContain('source document and this dialog are unchanged');await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(mocks.createSearchableOcrCopy.mock.calls.map(call=>call[0].requestId)).toEqual([request1,request2]);act(()=>ui.unmount());});
it('retains processing errors without opening a copy',async()=>{mocks.createSearchableOcrCopy.mockRejectedValue(new Error('Unsupported OCR layout.'));const ui=await mount();await openSource(ui);launch(ui);await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(ui.root.findByProps({role:'alert'}).children.join('')).toBe('Unsupported OCR layout.');expect(ui.root.findAllByProps({'data-viewed-document':4})).toHaveLength(0);act(()=>ui.unmount());});
it('refuses a stale captured revision before native work',async()=>{const opened={...source,pages:[...source.pages]};const ui=await mount();await openSource(ui,opened);launch(ui);opened.revision=10;await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(mocks.createSearchableOcrCopy).not.toHaveBeenCalled();expect(ui.root.findByProps({role:'alert'}).children.join('')).toContain('document changed');act(()=>ui.unmount());});
it('does not launch page OCR while a searchable attempt owns the shared OCR modal',async()=>{let finish!:(value:null)=>void;mocks.createSearchableOcrCopy.mockReturnValue(new Promise<null>(resolve=>{finish=resolve;}));const ui=await mount();await openSource(ui);launch(ui);act(()=>button(ui,'Create searchable copy').props.onClick());act(()=>ui.root.findByProps({'aria-expanded':false}).props.onClick());const pageAction=ui.root.findAllByType('button').find(item=>item.children.join('')==='Recognize current page…');if(pageAction)act(()=>pageAction.props.onClick());expect(mocks.recognizePageOcr).not.toHaveBeenCalled();expect(ui.root.findAllByProps({'aria-labelledby':'searchable-ocr-title'})).toHaveLength(1);await act(async()=>finish(null));act(()=>ui.unmount());});
it('blocks direct open, close, save, print, keyboard, and dropped-file actions while the searchable dialog is open',async()=>{const ui=await mount();await openSource(ui);launch(ui);const callsBefore=mocks.openDocument.mock.calls.length;act(()=>ui.root.findByProps({'aria-expanded':false}).props.onClick());const openAction=ui.root.findAllByType('button').find(item=>item.children.some(child=>child==='Open… '))!,menuSave=ui.root.findAllByType('button').find(item=>item.children.some(child=>child==='Save a copy… '))!,globalSave=ui.root.findByProps({'aria-label':'Save a copy'}),print=ui.root.findByProps({'aria-label':'Print'});act(()=>{openAction.props.onClick();menuSave.props.onClick();globalSave.props.onClick();print.props.onClick();});const close=ui.root.findByProps({'aria-label':'Close source.pdf'});act(()=>close.props.onClick());act(()=>{keydown?.({ctrlKey:true,key:'s',preventDefault:vi.fn(),target:{closest:()=>null,matches:()=>false}} as unknown as KeyboardEvent);dragDrop?.({payload:{type:'drop',paths:['C:/other.pdf']}});});expect(mocks.openDocument).toHaveBeenCalledTimes(callsBefore);expect(mocks.closeDocument).not.toHaveBeenCalled();expect(mocks.saveCopy).not.toHaveBeenCalled();expect(mocks.reopenDocument).not.toHaveBeenCalled();expect(ui.root.findAllByType('dialog')).toHaveLength(1);expect(JSON.stringify(ui.toJSON())).toContain('Finish the current operation or dialog');act(()=>ui.unmount());});
