import { invoke, isTauri } from '@tauri-apps/api/core';
export { recoveryCommittedReopenRequired } from './recoveryErrors';
export type { RecoveryCommittedReopenRequired } from './recoveryErrors';
import type { DocumentInfo, PageEdit } from './model';
import type { DocumentPageLabels } from './pageLabels';
export const native = isTauri();
export type RecoveryOffer = { revision: number; currentPage: number };
export type PasswordChallenge = { status: 'password_required'; request_id: number; name: string; incorrect: boolean };
export type OpenResult = { status: 'opened'; document: DocumentInfo; recovery?: RecoveryOffer | null } | PasswordChallenge;
export async function openDocument(example = false): Promise<OpenResult | null> {
  if (!native) throw new Error('Open the Windows desktop application to load a PDF. This browser view previews the workspace only.');
  return example ? { status: 'opened', document: await invoke<DocumentInfo>('open_example') } : invoke<OpenResult | null>('open_document');
}
export const closeDocument = (id: number) => invoke<void>('close_document', { id });
export const reopenDocument = (path: string) => invoke<OpenResult>('reopen_document', { path });
export type RecoveryCheckpointReceipt = { documentId: number; revision: number; currentPage: number };
export type RecoveryDiscardReceipt = { documentId: number; revision: number };
export type RecoveryRestoreResult = { document: DocumentInfo; currentPage: number };
export const checkpointRecovery = (id: number, revision: number, currentPage: number) => invoke<RecoveryCheckpointReceipt>('checkpoint_recovery', { id, revision, currentPage });
export const discardRecovery = (id: number, revision: number) => invoke<RecoveryDiscardReceipt>('discard_recovery', { id, revision });
export const restoreRecovery = () => invoke<RecoveryRestoreResult | null>('restore_recovery');
export const keepRecoveredEdits = (id: number, revision: number) => invoke<RecoveryRestoreResult>('keep_recovered_edits', { id, revision });
export const openOriginal = (id: number, revision: number) => invoke<DocumentInfo>('open_original', { id, revision });
export const unlockDocument = (requestId: number, password: string) => invoke<OpenResult>('unlock_document', { requestId, password });
export const cancelPasswordRequest = (requestId: number) => invoke<void>('cancel_password_request', { requestId });
export type OcrCapability = {
  available: boolean; reason: string | null; language: 'eng' | null;
  searchablePdfAvailable: boolean; searchablePdfReason: string | null; searchablePdfDpi: number | null;
  searchablePdfMaxPages: number; searchablePdfMaxPixels: number; searchablePdfMaxWords: number;
  searchablePdfMaxTextBytes: number; searchablePdfCharacters: string | null;
};
export type OcrRequest = { requestId: string; id: number; revision: number; page: number };
export type OcrReceipt = { status: 'recognized' | 'no_text'; requestId: string; documentId: number; revision: number; page: number; dpi: 150; language: 'eng'; width: number; height: number; text: string };
export type OcrCancelAck = { requestId: string; status: 'cancelled' | 'already_cancelled' | 'finished' };
export const ocrCapability = () => invoke<OcrCapability>('ocr_capability');
export const recognizePageOcr = (request: OcrRequest) => invoke<OcrReceipt>('recognize_page_ocr', request);
export const cancelPageOcr = (requestId: string) => invoke<OcrCancelAck>('cancel_page_ocr', { requestId });
export type SearchableOcrCopyRequest = { requestId: string; documentId: number; revision: number };
export const createSearchableOcrCopy = (request: SearchableOcrCopyRequest) => invoke<SavedCopy | null>('create_searchable_ocr_copy', request);
export type PrintResult = { status: 'cancelled' } | { status: 'submitted'; pages: number };
export const printDocument = (id: number, revision: number, currentPage: number, requestId: string) => invoke<PrintResult>('print_document', { id, revision, currentPage, requestId });
export const cancelPrint = (requestId: string) => invoke<void>('cancel_print', { requestId });
export type DocumentPropertiesInfo = {
  version: string | null; source_size_bytes: number; page_count: number;
  metadata: { name: string; value: string; truncated: boolean }[];
  page_dimensions: { width_points: number; height_points: number; count: number }[];
  page_dimensions_truncated: boolean;
  security: { encrypted: boolean | null; handler_revision: number | null; print_high_quality: boolean | null; print_low_quality_only: boolean | null; modify_contents: boolean | null; assemble_document: boolean | null; fill_existing_forms: boolean | null };
  reported_signature_count: number | null; signature_validation: 'not_performed';
};
export const documentProperties = (id: number, revision: number) => invoke<DocumentPropertiesInfo>('document_properties', { id, revision });
export const documentPageLabels = (id: number, revision: number) => invoke<DocumentPageLabels>('document_page_labels', { id, revision });
export const dependencyNotices = () => invoke<string>('dependency_notices');
export const pageText = (id: number, page: number, revision: number) => invoke<string>('page_text', { id, page, revision });
export type PageTextGeometry = {
  id: number; page: number; revision: number; status: 'ok' | 'unsupported'; truncated: boolean;
  characters: { text: string; bounds: { x: number; y: number; width: number; height: number } | null; angle: number }[];
  reason: string | null;
};
export const pageTextGeometry = (id: number, page: number, revision: number) => invoke<PageTextGeometry>('page_text_geometry', { id, page, revision });
export type BookmarkList = { items: { title: string; page: number | null; depth: number }[]; truncated: boolean };
export const documentBookmarks = (id: number, revision: number) => invoke<BookmarkList>('document_bookmarks', { id, revision });
export const editPages = (id: number, revision: number, edit: PageEdit, currentPage: number) => invoke<DocumentInfo>('edit_pages', { id, revision, edit, currentPage });
export type SavedCopy = { path: string; document: DocumentInfo };
export const saveCopy = (id: number, revision: number, pages?: number[]) => invoke<SavedCopy | null>('save_copy', { id, revision, pages: pages ?? null });
export type CreatePdfOptions = { pageSize: 'letter' | 'a4'; orientation: 'auto' | 'portrait' | 'landscape'; marginPoints: number };
export const createPdfFromImage = (options: CreatePdfOptions) => invoke<SavedCopy | null>('create_pdf_from_image', { options });
export type ImagePdfSource = { sourceId: string; name: string };
export type ImagePdfSelection = { selectionId: string; sources: ImagePdfSource[] };
export const chooseImagePdfSources = (replaceSelectionId?: string) => invoke<ImagePdfSelection | null>('choose_image_pdf_sources', { replaceSelectionId: replaceSelectionId ?? null });
export const createPdfFromImages = (selectionId: string, sourceIds: string[], options: CreatePdfOptions) => invoke<SavedCopy | null>('create_pdf_from_images', { selectionId, sourceIds, options });
export const cancelImagePdfSources = (selectionId: string) => invoke<void>('cancel_image_pdf_sources', { selectionId });
export type ImageReplacementTarget = { selectionId:string;documentId:number;revision:number;page:number;displayWidth:number;displayHeight:number;pixelWidth:number;pixelHeight:number;acceptedFormats:['png','jpeg'];mode:'newCopy' };
export const inspectImageReplacementTarget=(documentId:number,revision:number,page:number)=>invoke<ImageReplacementTarget>('inspect_image_replacement_target',{documentId,revision,page});
export const replacePdfImageCopy=(selectionId:string,documentId:number,revision:number)=>invoke<SavedCopy|null>('replace_pdf_image_copy',{selectionId,documentId,revision});
export const cancelImageReplacement=(selectionId:string)=>invoke<void>('cancel_image_replacement',{selectionId});
export type TextReplacementTarget={selectionId:string;documentId:number;revision:number;page:number;runId:'run-0';text:string;bounds:{x:number;y:number;width:number;height:number};maxBytes:number;mode:'newCopy'};
export const inspectTextReplacementTarget=(documentId:number,revision:number,page:number)=>invoke<TextReplacementTarget>('inspect_text_replacement_target',{documentId,revision,page});
export const replacePdfTextCopy=(selectionId:string,documentId:number,revision:number,runId:string,replacement:string)=>invoke<SavedCopy|null>('replace_pdf_text_copy',{selectionId,documentId,revision,runId,replacement});
export const cancelTextReplacement=(selectionId:string)=>invoke<void>('cancel_text_replacement',{selectionId});
export type PageImageFormat = 'png' | 'jpeg';
export type PageImageExportRequest = { id: number; revision: number; page: number; dpi: 72 | 150 | 300; format?: PageImageFormat };
export type PageImageExport = { path: string; documentId: number; revision: number; page: number; dpi: number; width: number; height: number; format: PageImageFormat };
export const exportPageImage = (request: PageImageExportRequest) => invoke<PageImageExport | null>('export_page_image', request);
export type RasterRedactionRect = { x: number; y: number; width: number; height: number };
export type RedactDocumentRequest = { id: number; revision: number; page: number; rectangles: RasterRedactionRect[] };
export const redactDocument = (request: RedactDocumentRequest) => invoke<SavedCopy | null>('redact_document', request);
export type FormTextField = { kind: 'text'; fieldId: string; name: string; page: number; value: string; maxLength: number | null };
export type FormCheckboxField = { kind: 'checkbox'; fieldId: string; name: string; page: number; checked: boolean };
export type FormRadioField = { kind: 'radio'; fieldId: string; name: string; page: number; options: { optionId: string; label: string }[]; selectedOptionId: string | null };
export type FormChoiceField = { kind: 'choice'; fieldId: string; name: string; page: number; presentation: 'dropdown' | 'list'; options: { optionId: string; label: string }[]; selectedOptionId: string | null };
export type FormField = FormTextField | FormCheckboxField | FormRadioField | FormChoiceField;
export type FormPatch = { fieldId: string; kind: 'text'; value: string } | { fieldId: string; kind: 'checkbox'; checked: boolean } | { fieldId: string; kind: 'radio'; optionId: string } | { fieldId: string; kind: 'choice'; optionId: string | null };
export type DocumentFormFields = { documentId: number; revision: number; status: 'supported' | 'unsupported'; reason: string | null; input: 'printable-ascii'; valueByteLimit: number; fields: FormField[] };
export const documentFormFields = (id: number, revision: number) => invoke<DocumentFormFields>('document_form_fields', { id, revision });
export const fillFormCopy = (id: number, revision: number, values: FormPatch[]) => invoke<SavedCopy | null>('fill_form_copy', { id, revision, values });
export const combineDocuments = (first: { id: number; revision: number }, second: { id: number; revision: number }) => invoke<SavedCopy | null>('combine_documents', { first, second });
export const insertPagesCopy = (target: { id: number; revision: number }, donor: { id: number; revision: number }, at: number) => invoke<SavedCopy | null>('insert_pages_copy', { target, donor, at });
export const replacePagesCopy = (target: { id: number; revision: number }, donor: { id: number; revision: number }, start: number, count: number) => invoke<SavedCopy | null>('replace_pages_copy', { target, donor, start, count });
export type CommentRect = { x: number; y: number; width: number; height: number };
export type CommentNote = { id: string; page: number; rect: CommentRect | null; contents: string };
export type DocumentComments = { documentId: number; revision: number; status: 'supported' | 'unsupported'; reason: string | null; notes: CommentNote[] };
export const documentComments = (id: number, revision: number) => invoke<DocumentComments>('document_comments', { id, revision });
export const createComment = (id: number, revision: number, page: number, rect: CommentRect, contents: string, currentPage: number) => invoke<DocumentInfo>('create_comment', { id, revision, page, rect, contents, currentPage });
export const updateComment = (id: number, revision: number, noteId: string, contents: string, currentPage: number) => invoke<DocumentInfo>('update_comment', { id, revision, noteId, contents, currentPage });
export const deleteComment = (id: number, revision: number, noteId: string, currentPage: number) => invoke<DocumentInfo>('delete_comment', { id, revision, noteId, currentPage });
export type Annotation = { id: string; kind: 'note' | 'highlight'; page: number; rect: CommentRect | null; quads?: CommentRect[] | null; contents: string | null };
export type DocumentAnnotations = { documentId: number; revision: number; status: 'supported' | 'unsupported'; reason: string | null; annotations: Annotation[] };
export const documentAnnotations = (id: number, revision: number) => invoke<DocumentAnnotations>('document_annotations', { id, revision });
export const createHighlight = (id: number, revision: number, page: number, rect: CommentRect, contents: string | null, currentPage: number) => invoke<DocumentInfo>('create_highlight', { id, revision, page, rect, contents, currentPage });
export const createTextHighlight = (id: number, revision: number, page: number, start: number, end: number, contents: string | null, currentPage: number) => invoke<DocumentInfo>('create_text_highlight', { id, revision, page, start, end, contents, currentPage });
export const updateHighlight = (id: number, revision: number, annotationId: string, contents: string | null, currentPage: number) => invoke<DocumentInfo>('update_highlight', { id, revision, annotationId, contents, currentPage });
export const deleteHighlight = (id: number, revision: number, annotationId: string, currentPage: number) => invoke<DocumentInfo>('delete_highlight', { id, revision, annotationId, currentPage });
export type SplitOutput = { folder: string; files: { path: string; first_page: number; last_page: number; page_count: number }[] };
export const splitDocument = (id: number, revision: number, pagesPerFile: number) => invoke<SplitOutput | null>('split_document', { id, revision, pagesPerFile });
export type CropInsets = { top: number; right: number; bottom: number; left: number };
export const cropPage = (id: number, page: number, revision: number, rect: { x: number; y: number; width: number; height: number }, currentPage: number) => invoke<DocumentInfo>('crop_page', { id, page, revision, rect, currentPage });
export const cropPages = (id: number, revision: number, pages: number[], insets: CropInsets, currentPage: number) => invoke<DocumentInfo>('crop_pages', { id, revision, pages, insets, currentPage });
export const resetCrops = (id: number, revision: number, pages: number[], currentPage: number) => invoke<DocumentInfo>('reset_crops', { id, revision, pages, currentPage });
export async function renderPage(id: number, page: number, width: number) {
  const bytes = await invoke<ArrayBuffer>('render_page', { id, page, width });
  return URL.createObjectURL(new Blob([bytes], { type: 'image/png' }));
}
