import{useEffect,useRef,useState}from'react';
import type{ImageReplacementTarget,SavedCopy}from'./bridge';
import{validateImageReplacementTarget,type CancelImageReplacement,type ReplacePdfImageCopy}from'./imageReplacement';
import s from'./CombineDialog.module.css';
export default function ImageReplacementDialog({target,replace,cancel,opened,close}:{target:ImageReplacementTarget;replace:ReplacePdfImageCopy;cancel:CancelImageReplacement;opened:(copy:SavedCopy)=>void;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),retained=useRef(true),active=useRef(false);const[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const invalid=validateImageReplacementTarget(target);
 useEffect(()=>{dialog.current?.showModal();return()=>{if(retained.current)void cancel(target.selectionId);};},[cancel,target.selectionId]);
 const release=async()=>{if(active.current)return;active.current=true;setWorking(true);setError('');try{await cancel(target.selectionId);retained.current=false;close();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{active.current=false;setWorking(false);}};
 const apply=async()=>{if(active.current||invalid)return;active.current=true;setWorking(true);setError('');setNotice('');try{const result=await replace(target);if(result){retained.current=false;opened(result);close();}else setNotice('Replacement or output selection canceled. The target and source document are unchanged.');}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{active.current=false;setWorking(false);}};
 return <dialog ref={dialog} className={s.dialog} aria-labelledby="image-replacement-title" onCancel={event=>{event.preventDefault();if(!working)void release();}}><h2 id="image-replacement-title">Replace the page image in a new copy</h2><p>Page {target.page+1} contains one supported flat full-page image. Choose a PNG or JPEG with exactly {target.pixelWidth} × {target.pixelHeight} pixels.</p><p className={s.preview}>This creates and opens a clean new PDF copy. The source, its history, undo, and redo stay unchanged. Arbitrary images, cropped or rotated pages, layouts, shared resources, masks, forms, and reflow are not supported.</p>{invalid&&<p role="alert">{invalid}</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{working&&<p role="status">Waiting for the native image and PDF pickers…</p>}<div className={s.actions}><button disabled={working} onClick={()=>void release()}>Cancel</button><button className={s.confirm} disabled={working||!!invalid} onClick={()=>void apply()}>Choose image and save copy</button></div></dialog>;
}
