import { act,create,type ReactTestRenderer } from 'react-test-renderer';
import { expect,it,vi } from 'vitest';
import SearchableOcrDialog from './SearchableOcrDialog';
import type { SavedCopy } from './bridge';
import type { SearchableOcrCapability } from './searchableOcr';
const available:SearchableOcrCapability={searchablePdfAvailable:true,searchablePdfReason:null,searchablePdfDpi:150,searchablePdfMaxPages:32,searchablePdfMaxPixels:33_554_432,searchablePdfMaxWords:100_000,searchablePdfMaxTextBytes:8_388_608,searchablePdfCharacters:'printable ASCII words only'};
const request={requestId:'document-ocr-7',documentId:7,revision:11};
const saved:SavedCopy={path:'C:/searchable.pdf',document:{id:8,name:'searchable.pdf',path:'C:/searchable.pdf',pages:[{width:612,height:792}],revision:0,dirty:false,can_undo:false,can_redo:false}};
const button=(ui:ReactTestRenderer,text:string)=>ui.root.findAllByType('button').find(item=>item.children.join('')===text)!;
async function mount(createCopy=vi.fn().mockResolvedValue(saved),cancel=vi.fn().mockResolvedValue({requestId:request.requestId,status:'cancelled'}),capability=available){const close=vi.fn(),opened=vi.fn();let ui!:ReactTestRenderer;await act(async()=>{ui=create(<SearchableOcrDialog capability={capability} request={request} create={createCopy} cancel={cancel} close={close} opened={opened}/>,{createNodeMock:element=>element.type==='dialog'?{showModal:vi.fn()}:null});});return{ui,createCopy,cancel,close,opened};}
it('discloses the fixed destructive profile and opens only a returned clean copy',async()=>{const{ui,createCopy,close,opened}=await mount();const text=JSON.stringify(ui.toJSON());expect(text).toContain('every current page at fixed 150 DPI');expect(text).toContain('printable ASCII words');expect(text).toContain('33,554,432 pixels');await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(createCopy).toHaveBeenCalledWith(request);expect(opened).toHaveBeenCalledWith(saved);expect(close).toHaveBeenCalledOnce();act(()=>ui.unmount());});
it('keeps the dialog on picker cancellation and errors',async()=>{const createCopy=vi.fn().mockResolvedValueOnce(null).mockRejectedValueOnce(new Error('Unsupported layout.'));const{ui,close}=await mount(createCopy);await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(ui.root.findByProps({role:'status'}).children.join('')).toContain('source document');expect(close).not.toHaveBeenCalled();await act(async()=>button(ui,'Create searchable copy').props.onClick());expect(ui.root.findByProps({role:'alert'}).children.join('')).toBe('Unsupported layout.');act(()=>ui.unmount());});
it('cancels the exact active request once and validates the acknowledgement',async()=>{let finish!:(value:SavedCopy|null)=>void;const createCopy=vi.fn(()=>new Promise<SavedCopy|null>(resolve=>{finish=resolve;}));const cancel=vi.fn().mockResolvedValue({requestId:request.requestId,status:'cancelled'});const{ui}=await mount(createCopy,cancel);act(()=>button(ui,'Create searchable copy').props.onClick());expect(button(ui,'Cancel OCR')).toBeTruthy();await act(async()=>button(ui,'Cancel OCR').props.onClick());expect(cancel).toHaveBeenCalledWith(request.requestId);expect(button(ui,'Cancel OCR').props.disabled).toBe(true);await act(async()=>finish(null));act(()=>ui.unmount());});
it('latches cancellation synchronously and does not retry a rejected transport call for the same request',async()=>{let finish!:(value:SavedCopy|null)=>void,rejectCancel!:(reason:Error)=>void;const createCopy=vi.fn(()=>new Promise<SavedCopy|null>(resolve=>{finish=resolve;}));const cancel=vi.fn(()=>new Promise<never>((_,reject)=>{rejectCancel=reject;}));const{ui}=await mount(createCopy,cancel);act(()=>button(ui,'Create searchable copy').props.onClick());const handler=button(ui,'Cancel OCR').props.onClick;act(()=>{handler();handler();});expect(cancel).toHaveBeenCalledTimes(1);await act(async()=>rejectCancel(new Error('Cancel transport failed.')));expect(ui.root.findByProps({role:'alert'}).children.join('')).toBe('Cancel transport failed.');act(()=>handler());expect(cancel).toHaveBeenCalledTimes(1);await act(async()=>finish(null));act(()=>ui.unmount());});
it('fails closed for unavailable or mismatched capability without native work',async()=>{const unavailable={...available,searchablePdfAvailable:false,searchablePdfReason:'Verified OCR is unavailable.'};const{ui,createCopy}=await mount(vi.fn(),vi.fn(),unavailable);expect(ui.root.findByProps({role:'alert'}).children.join('')).toBe('Verified OCR is unavailable.');expect(button(ui,'Create searchable copy').props.disabled).toBe(true);expect(createCopy).not.toHaveBeenCalled();act(()=>ui.unmount());});
