import{useEffect,useRef,useState}from'react';
import type{SavedCopy,TextReplacementTarget}from'./bridge';
import{validateTextReplacement,validateTextReplacementTarget,type CancelTextReplacement,type ReplacePdfTextCopy}from'./textReplacement';
import s from'./CombineDialog.module.css';
export default function TextReplacementDialog({target,replace,cancel,opened,close}:{target:TextReplacementTarget;replace:ReplacePdfTextCopy;cancel:CancelTextReplacement;opened:(copy:SavedCopy)=>void;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),retained=useRef(true),active=useRef(false);const[value,setValue]=useState(target.text),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const invalidTarget=validateTextReplacementTarget(target),invalidValue=validateTextReplacement(value,target.maxBytes);
 useEffect(()=>{dialog.current?.showModal();return()=>{if(retained.current)void cancel(target.selectionId);};},[cancel,target.selectionId]);
 const release=async()=>{if(active.current)return;active.current=true;setWorking(true);setError('');try{await cancel(target.selectionId);retained.current=false;close();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{active.current=false;setWorking(false);}};
 const apply=async()=>{if(active.current||invalidTarget||invalidValue)return;active.current=true;setWorking(true);setError('');setNotice('');try{const result=await replace(target,value);if(result){retained.current=false;opened(result);close();}else setNotice('Save canceled. The target, replacement text, and source document are unchanged.');}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{active.current=false;setWorking(false);}};
 return <dialog ref={dialog} className={s.dialog} aria-labelledby="text-replacement-title" onCancel={event=>{event.preventDefault();if(!working)void release();}}><h2 id="text-replacement-title">Replace strict text in a new copy</h2><p>Page {target.page+1} contains one supported Helvetica text run. Replacement must remain exactly {target.maxBytes} printable-ASCII bytes and preserve its exact width.</p><label>Replacement text<input value={value} disabled={working||!!invalidTarget} maxLength={target.maxBytes} onChange={event=>setValue(event.target.value)}/></label><p className={s.preview}>This creates and opens a clean new PDF copy. The source, its history, undo, and redo stay unchanged. Other fonts, Unicode, reflow, multiple runs, cropped or rotated pages, and arbitrary layout editing are not supported.</p>{invalidTarget&&<p role="alert">{invalidTarget}</p>}{!invalidTarget&&invalidValue&&<p role="alert">{invalidValue}</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{working&&<p role="status">Waiting for the native PDF picker…</p>}<div className={s.actions}><button disabled={working} onClick={()=>void release()}>Cancel</button><button className={s.confirm} disabled={working||!!invalidTarget||!!invalidValue} onClick={()=>void apply()}>Save replacement copy</button></div></dialog>;
}
